deploy_script_version: '1.0'

environment:
  app: 'ru'
  environment: 'prod'
  datacenters:
    - dc1
  consul_host: '95.213.134.243'

services:

  config-pusher:
    mem_limit: 4g
    cpu_limit: 200
    version: null