apiVersion: apps/v1
kind: Deployment
metadata:
  name: service-db-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: service-db
  template:
    metadata:
      labels:
        app: service-db
    spec:
      containers:
        - name: service-db
          image: postgres:14.7-alpine
          ports:
            - containerPort: 5432