apiVersion: apps/v1
kind: Deployment
metadata:
  name: service-db-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: service-db
  template:
    metadata:
      labels:
        app: service-db
    spec:
      containers:
        - name: service-db
          image: postgres:14.7-alpine
          ports:
            - containerPort: 5432

---

apiVersion: v1
kind: Service
metadata:
  name: service-db-service
spec:
  selector:
    app: service-db
  ports:
    - protocol: TCP
      port: 5432
      targetPort: 5432