spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/FunScrut
    username: postgres
    password: 191220#destin
  graphql:
    enable: true
    cors:
      allowed-origins: true
    schema:
      printer:
        enabled: true

server:
  port: 8082
  error:
    include-stacktrace: never

logging:
  level:
    org:
      jooq:
        tools:
          LoggerListener: debug