graphql:
  datetime:
    scalars:
      local-date-time:
        format: yyyy-MM-DD'T'HH:mm
      local-date:
        format: yyyy-MM-DD

spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/FunScrut2
    username: postgres
    password: 191220#destin
  graphql:
    enable: true
    cors:
      allowed-origins: true
    schema:
      printer:
        enabled: true
  application:
    name: ru-service
  cloud:
    consul:
      host: 192.168.99.100
      port: 8500
      discovery:
        register: false

server:
  port: ${NOMAD_HOST_PORT_http:8090}
  error:
    include-stacktrace: never

logging:
  level:
    org:
      jooq:
        tools:
          LoggerListener: debug