name: Build and Deploy

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    if: |
      contains(github.event.head_commit.message, '[deploy-back]') ||
      contains(github.event.pull_request.title, '[deploy-back]')
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3  

    - name: Set up JDK
      uses: actions/setup-java@v3
      with:
        java-version: '17'  # Укажите версию JDK
        distribution: 'corretto'
        cache: gradle

    - name: Verify Java version
      run: java -version
      
    - name: Setup Gradle
      uses: gradle/gradle-build-action@v3
      with:
        gradle-version: 7.4.2
        
    - name: Build with Gradle
      run: ./gradlew build --console=plain
      
    - name: Upload artifact
      uses: actions/upload-artifact@v3
      with:
        name: my-app
        path: backend/domain/ru-client/build/libs/ru-client-0.0.2-SNAPSHOT.jar  # Путь к сгенерированному JAR файлу.

  deploy:
    runs-on: ubuntu-latest
    needs: build

    steps:
    - name: Download artifact
      uses: actions/download-artifact@v3
      with:
        name: my-app
        path: ./artifact

    - name: Copy files via SCP
      env:
        SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}
      run: |
        mkdir -p ~/.ssh
        echo "${{ secrets.SSH_PRIVATE_KEY }}" > ~/.ssh/id_rsa
        chmod 600 ~/.ssh/id_rsa
        scp -o StrictHostKeyChecking=no ./artifact/ru-client-0.0.2-SNAPSHOT.jar root@funscrut.online:${{ secrets.DESTINATION_FOLDER_BACK }}
        
    - name: Restart Docker Compose
      env:
       SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}
      run: |
       ssh -o StrictHostKeyChecking=no root@funscrut.online << 'EOF'
       cd /home/Nikolay/funScrut
       docker compose up -d --build
       EOF
