
name: Deploy frontend

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    if: |
      contains(github.event.head_commit.message, '[deploy-front]') ||
      contains(github.event.pull_request.title, '[deploy-front]')
    runs-on: ubuntu-latest

    steps:
    - name: List files in frontend directory
      run: ls -R frontend
      
    - name: List files in build directory
      run: ls -R frontend/public

    - name: Upload artifact
      uses: actions/upload-artifact@v3
      with:
        name: my-app-front
        path: frontend/public 

  deploy:
    runs-on: ubuntu-latest
    needs: build

    steps:
    - name: Download artifact
      uses: actions/download-artifact@v3
      with:
        name: my-app-front
        path: ./artifact
        
    - name: Verify artifact downloaded
      run: ls -l ./artifact  # Проверка, что артефакт был загружен

    - name: Copy files via SCP
      env:
        SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}
      run: |
        mkdir -p ~/.ssh
        echo "${{ secrets.SSH_PRIVATE_KEY }}" > ~/.ssh/id_rsa
        chmod 600 ~/.ssh/id_rsa
        scp -r -o StrictHostKeyChecking=no ./artifact/public/ root@funscrut.online:${{ secrets.DESTINATION_FOLDER_FRONTEND }}
