name: Build and Deploy

on:
  push:
    branches:
      - main  # Ветка, на которую будет срабатывать событие

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3  

    - name: Set up JDK
      uses: actions/setup-java@v3
      with:
        java-version: '17'  # Укажите версию JDK
        distribution: 'temurin'        

    - name: Build with Gradle
      run: ./gradlew build  # Или используйте Maven: mvn clean package

    - name: Verify JAR file exists
      run: ls -l build/libs/  # Проверка, что JAR файл существует

    - name: Upload artifact
      uses: actions/upload-artifact@v3
      with:
        name: my-app
        path: build/libs/ru-client-0.0.2-SNAPSHOT.jar  # Путь к сгенерированному JAR файлу

  deploy:
    runs-on: ubuntu-latest
    needs: build

    steps:
    - name: Download artifact
      uses: actions/download-artifact@v3
      with:
        name: my-app
        path: ./artifact
        
    - name: Verify artifact downloaded
      run: ls -l ./artifact  # Проверка, что артефакт был загружен

    - name: Copy files via SCP
      env:
        SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}
      run: |
        mkdir -p ~/.ssh
        echo "${{ secrets.SSH_PRIVATE_KEY }}" > ~/.ssh/id_rsa
        chmod 600 ~/.ssh/id_rsa
        scp -o StrictHostKeyChecking=no ./artifact/ru-client-0.0.2-SNAPSHOT.jar user@funscrut.online:${{ secrets.DESTINATION_FOLDER }}
